### ISSUE TITLE
MIT license and merging into GopherJS repo.

### ISSUE THREAD

**Issue by shurcooL** [go-on/gopherjslib#7]
Hey @metakeule,

This library is MIT licensed, which is permissive and great. I'd like to temporarily merge my fork of this library into the core GopherJS repo in order to help some future refactors. GopherJS also uses a permissive license:

https://github.com/gopherjs/gopherjs/blob/master/LICENSE

I'd prefer not to maintain multiple LICENSE files in the same repo, so are you okay to donate this code (or rather my forked version, which is slightly modified) to the GopherJS project and inherit its current license?

Thanks!

**Comment by metakeule** [comment]
Hey shurcooL, 

I am fine with it. Go ahead!

Regards

**Comment by metakeule** [comment]
(In fact it has been part of gopherjs and I had to make a library out of it as requested by Richard. ;-)

**Comment by shurcooL** [comment]
> I am fine with it. Go ahead!

Awesome, thank you very much @metakeule!

By the way, this library and its API have been _extremely_ helpful to me, and allowed me to create [`gopherjs_http.NewFS`](https://godoc.org/github.com/shurcooL/go/gopherjs_http#NewFS), merge https://github.com/shurcooL/Go-Package-Store/pull/18, and many other cool things! So thank you for making it and helping push GopherJS have a Go API. :)
